apiVersion: v1
kind: Secret
metadata:
  name: user-service-secrets
type: Opaque
stringData:
  DB_URL: "jdbc:postgresql://postgresql-primary-hl.dev/sagitta"
  DB_USERNAME: "dev@sagitta"
  DB_PASSWORD: "password@sagitta"
